### ISSUE TITLE
Ubuntu 24.04/GDM3 Gnome graphics bug

### ISSUE THREAD

**Issue by Taikakim** [git-moss/ProjectConverter#11]
![image](https://github.com/git-moss/ProjectConverter/assets/21206467/a3da15a3-d1b6-4ea9-9eea-d146abaef573)

I seem to have a gfx bug. I'm on 6.8.0-31-lowlatency #31.1-Ubuntu SMP PREEMPT_DYNAMIC, and have an I7 6700 HP Elitedesk SFF desktop with integrated Intel HD graphics.

**Comment by git-moss** [comment]
Thanks for reporting! I already fixed this in ConvertWithMoss but it seems I only partially ported the fix to ProjectConverter. Will be fixed in the next update!
