### ISSUE TITLE
"Writing audio file" taking forever

### ISSUE THREAD

**Issue by pingarelho** [git-moss/ProjectConverter#13]
I'm trying to convert Studio One dawproject files to reaper projects and the "writing audio file" parts of the process are taking much longer than they are supposed to considering it should be just a matter of unpacking these files and copying them, right?

**Comment by git-moss** [comment]
The ZIP implementation in Java is pretty slow. But it should not take "forever". How big is the file?

**Comment by pingarelho** [comment]
2.4gb, each ~30mb audio file was taking 1 minute to unpack.

**Comment by git-moss** [comment]
That's really bad. Not sure if I can do anything about it. Could you provide me an example?
