### ISSUE TITLE
Support FLAC

### ISSUE THREAD

**Issue by adrienneteicher** [git-moss/ProjectConverter#14]
Hi, converting a project rn and I get this error message

"Clip type FLAC not supported."

Is FLAC support coming?

Thanks

**Comment by git-moss** [comment]
Should be easy if the format is kept. Will add it to my todo list.

**Comment by adrienneteicher** [comment]
cool. thanks!!

**Comment by git-moss** [comment]
Will be in the next update.

**Comment by adrienneteicher** [comment]
nice one. thanks!
