### ISSUE TITLE
MIDI items doesn't translate correctly

### ISSUE THREAD

**Issue by Kabraxist** [git-moss/ProjectConverter#15]
Hey Moss,

I have this Reaper project handed to me by a third party. It's a simple project with no gimmicks.
Somehow the timings, contents and the count on the converted .dawproject file doesn't match the original project. Attached I'm sending the original and the converted file's screenshots. You can see most of the items aligned to the start of the project, and the consequent MIDI items are straight out empty.

![image](https://github.com/user-attachments/assets/ad9ae9de-bbb5-4e1f-8cf5-7c5b9cb40842)
![image](https://github.com/user-attachments/assets/6cfd0176-361f-4784-bd7c-84959ee7defb)

I can share the original project privately as well.

**Comment by git-moss** [comment]
Yes, please send the original project. You can PM me the link on KVR.
Does it contain continuous tempo changes? These are not supported.

**Comment by Kabraxist** [comment]
Sent it over Reaper forums - I don't had the permission on KVR :)

Forgot to add specs:
Reaper v7.24
Studio One 6.6.2

**Comment by git-moss** [comment]
The converted file looks fine to me in Bitwig, therefore, I assume the issue is on the side of Studio One.
I already forwarded your issue to them.

**Comment by git-moss** [comment]
FYI Presonus told me that they can currently not handle double wrapped MIDI clips (works only for Audio clips).
