### ISSUE TITLE
Reaper crash while opening converted DAWproject from StudioOne 7

### ISSUE THREAD

**Issue by Hipox** [git-moss/ProjectConverter#16]
Hi, I uploaded the converted RPP for you to check what's going on. I can send over also the DAWproject, elt me know.

[The Fall (v17-1-toReaper).zip](https://github.com/user-attachments/files/17534526/The.Fall.v17-1-toReaper.zip)

**Comment by git-moss** [comment]
I can open the project without a problem (Reaper 7.26).
Since I do not have the WAV files, maybe the issue is with them? Can you try to copy the RPP somewhere else without the rest of the project data and open it?
