### ISSUE TITLE
Fairly simple DawProject missing 95% of audio clips in conversion process

### ISSUE THREAD

**Issue by rclough** [git-moss/ProjectConverter#17]
## Issue Summary

Hello, thanks for you work on ProjectConverter, I'm greatly appreciative of open source projects. 

I'm trying to move a project from Cubase (which has OMF/AAF support) into Reaper by converting it to a DawProject file after I consolidated all of the tracks into a handful of related dialogue tracks. 

However, when I convert DawProject to Reaper with ProjectConverter, it only includes a couple of audio files from the beginning of the project, and ignores the rest of them.

## Environment Info

ProjectConverter v1.2.9
Windows 11 Pro
Cubase 14.0.5 Build 125 (x64) (Oct 20 2024)
Reaper 7.27

## About the source project

* The source project contains 1 video track (although I have tried converting a version with no video and the behavior is the same)
* There are 15 mono audio tracks (some are panned L or R)
* I'd estimate about 150-200 individual clips across all of the tracks
* Audio is in `.aif` format
* Project is about 8.5 minutes long
* apart from panning information and some clip level volumes, there is some simple crossfading at times
* The clips do have "titles" with the original filename on them

### Converting with the video track

Source file is 1.54 GB

Logs: 

```
Parsing source project: C:\Users\ryanc\Music\Music Projects\Mordrake\mordrake-export-2.dawproject
Validating project file...
Writing destination file(s) to: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\mordrake-export-2\745220ae-cffa-7964-80a3-8efb00000083.aif
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\mordrake-export-2\7ea235f4-2dc8-fae0-4ac6-dcad00000083.aif
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\mordrake-export-2\91964847-d518-ee93-fc1d-039400000083.aif
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\mordrake-export-2\49d0d1ae-d37d-084c-391c-1e7200000083.aif
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\mordrake-export-2\566ea59f-f864-ea7e-7bfc-b29e00000083.aif
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\mordrake-export-2\c337ea5e-a6e1-a13b-52fc-aed100000083.aif
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\mordrake-export-2\d2772311-20ce-e94b-f405-4a3d00000083.aif
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\mordrake-export-2\76c7733a-4000-da0f-3be6-a8ef00000083.aif
Done.
```

From the logs, I was immediately suspicious, as there should be far more audio files.

### Converting with no video track

Source file is 344MB

Logs:

```
Parsing source project: C:\Users\ryanc\Music\Music Projects\Mordrake\newproj-novideo.dawproject
Validating project file...
Writing destination file(s) to: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\newproj-novideo\745220ae-cffa-7964-80a3-8efb00000083.aif
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\newproj-novideo\7ea235f4-2dc8-fae0-4ac6-dcad00000083.aif
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\newproj-novideo\91964847-d518-ee93-fc1d-039400000083.aif
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\newproj-novideo\49d0d1ae-d37d-084c-391c-1e7200000083.aif
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\newproj-novideo\c337ea5e-a6e1-a13b-52fc-aed100000083.aif
Writing audio file: C:\Users\ryanc\Music\Music Projects\rp-dawproject-2\newproj-novideo\d2772311-20ce-e94b-f405-4a3d00000083.aif
Done.
```

Somehow, this one contains even fewer audio files (6 instead of 8), and I'm not sure why.

## Things I have Tried

* I tried importing the DawProject back into cubase, This works successfully for both the video and non-video version and looks just like the source project
* Tried with/without video
* Tried the DawProject scenes option - nothing is converted (as expected, I think)

Let me know if there's any additional information I can provide. I'm happy to privately share one of the project files if you'd like, just let me know how best to contact you. I'm also reasonably experienced in programming if you'd like me to try anything more complicated for debugging.

**Comment by rclough** [comment]
Here you can see the source project (Cubase on left) and what was converted and loaded into the reaper project (Right). Note the reaper project time scale is only 2 minutes compared to the cubase one which is 9 minutes

![Screenshot 2024-12-11 222545](https://github.com/user-attachments/assets/51404b02-dfd4-4f65-a731-cc1b67a147fb)

**Comment by git-moss** [comment]
Cubase Export is currently unusable. Nevertheless, I would like to take a look. Please send me an example, especially one with video would be interesting since I did not implement that yet. You can PM me on KVR or the Reaper forum (moss).

**Comment by git-moss** [comment]
Oh and also try Cubase 14.0.10 which fixes a couple of bugs.

**Comment by rclough** [comment]
Oof, that's sad to hear. I'll try the newer version and send you a PM a bit later when I get back to my studio.

FWIW, I don't need the video track as long as the audio is imported with the correct timing as I can import the video separately in reaper

**Comment by git-moss** [comment]
Thanks for the files and as suspected the export is not correct. The play range of the clip is not correct (or the clip position). I opened it in Bitwig and e.g. this is how one clip looks:
![Screenshot 2024-12-14 102556](https://github.com/user-attachments/assets/866fb0f6-48fa-4318-b9be-f4f54b445cc4)
Since I need to "roll-out" the wrapped clips in Reaper it will simply result in no clips at all.
I am afraid we need to wait for a fix by Steinberg.
