### ISSUE TITLE
Are you sure VST blob work?

### ISSUE THREAD

**Issue by mrlimbic** [git-moss/ProjectConverter#2]
Reaper bakes it's own data into VST/AU data blobs. 

So I'm not sure you can transfer them easily. I tried doing something similar a few years ago.

Does this actually work now? Has cockos changed the blob encoding?

**Comment by git-moss** [comment]
Yes, it works besides that I just fixed a bug with writing VST3 presets from Reaper to DAWproject.
Take a look at: https://github.com/git-moss/ProjectConverter/blob/80b66775f758ff76951dc7d395e5a60852b4efd8/src/main/java/de/mossgrabers/projectconverter/format/reaper/model/VstChunkHandler.java
