### ISSUE TITLE
Error when trying to convert from Reaper to Bitwig

### ISSUE THREAD

**Issue by TheScrutinizer** [git-moss/ProjectConverter#4]
As I have some older Reaper-projects which I want to convert to Bitwig Studio I was pleased to install your program ProjectConverter. Unfortunately I had some problems I hope you can look into.

The first Reaper-project I tried was opened in Reaper v7 on OSX and saved. Then I tried the conversion but got an error message.

The error message is:

Could not read or parse the source file:
Unsound folder structure.

I then made a new project in Reaper v7 and your ProjectConverte v1.1 had no problems converting it to DawProject-format.
It opened seamlessly in Bitwig Studio.

I look forward to have your feedback.

Tom

**Comment by git-moss** [comment]
Can you send me the project?

**Comment by TheScrutinizer** [comment]
tor. 19. okt. 2023 kl. 19:30 skrev Jürgen Moßgraber <
***@***.***>:

**Comment by git-moss** [comment]
Huh?

**Comment by TheScrutinizer** [comment]
What?

tor. 19. okt. 2023 kl. 21:26 skrev Jürgen Moßgraber <
***@***.***>:

**Comment by git-moss** [comment]
Could not see anything meaningful in your reply. Did you try to send a file?

**Comment by TheScrutinizer** [comment]
Ok. I'll zip the file.

tor. 19. okt. 2023 kl. 21:52 skrev Jürgen Moßgraber <
***@***.***>:

**Comment by git-moss** [comment]
It looks to me as if you did reply to the GitHub notification mail, maybe with attaching the file. This does not work, youhave to visit the GitHub website.

**Comment by TheScrutinizer** [comment]
I'm sorry I misunderstood. I thought you were sending me the questions by email.
Here's the file.

[Project.RPP.zip](https://github.com/git-moss/ProjectConverter/files/13057452/Project.RPP.zip)

**Comment by git-moss** [comment]
Thanks! Will be fixed in the next update!

**Comment by TheScrutinizer** [comment]
Thanks

**Comment by git-moss** [comment]
It is online.
