### ISSUE TITLE
Arch no install ?

### ISSUE THREAD

**Issue by robisme** [git-moss/ProjectConverter#5]
Hi,
I'm on EndeavourOs, and I can't install the Project converter.
I use debtap to convert it, but when I try to run pacman -U, I get error messages about libxxx.so.72 not being symlinkk
`erreur : la commande n’a pas pu être exécutée correctement
ldconfig: /usr/lib/libicuuc.so.72 n'est pas un lien symbolique
ldconfig: /usr/lib/libicuio.so.72 n'est pas un lien symbolique
ldconfig: /usr/lib/libicui18n.so.72 n'est pas un lien symbolique
ldconfig: /usr/lib/libicutu.so.72 n'est pas un lien symbolique
ldconfig: /usr/lib/libicutest.so.72 n'est pas un lien symbolique
ldconfig: /usr/lib/libicudata.so.72 n'est pas un lien symbolique
`

**Comment by git-moss** [comment]
I am afraid I cannot help you with that. I can only test on Ubuntu.
