### ISSUE TITLE
Multi-Out Plugins

### ISSUE THREAD

**Issue by Xylemflo** [git-moss/ProjectConverter#6]
I used the converter 1.1.3 to convert a project from Reaper 7.02 to Bitwig 5.0.11 on MacOS 14.0

I am not sure if this falls under "-Complex Routings..." mentioned in the manual, since many plugins have this feature. For Reaper, the process does not properly convert any tracks where you are using a multi-out instance of a plugin eg: Kontakt, XO, Battery, Sitala, etc. It loses all of the midi/audio routing for such instances, and leaves the tracks in a jumbled state in the destination project.  Is this a limitation of the dawproject specs at the moment, or does this need to be addressed by the converter?

ps: Thanks for all of your work on this !

**Comment by git-moss** [comment]
Just tested this with Bitwig and it does not work. Not sure if it is simply not implemented or not possible in the standard. You can create an issue in the DAWproject repo: https://github.com/bitwig/dawproject
