### ISSUE TITLE
From Dawproject to Reaper doesnt load midi information

### ISSUE THREAD

**Issue by adrian3014** [git-moss/ProjectConverter#7]
I am trying to convert a dawproject file (converted to dawproject from Studio One 6.5.0) to Reaper and it correctly loads everything except the MIDI information, which is empty in all the items. I am using Reaper 7.02

**Comment by git-moss** [comment]
Please try again with Studio One 6.5.1. If that still fails send me the project for testing.

**Comment by adrian3014** [comment]
I updated and tried again, same result. I also tried several of my projects and none of them work. To prevent incompatibility , I have saved a version removing all instruments and effects (which obv doesnt work either). I'll send you both the dawproject file, reaper result file and the studio one song file at this link : [https://drive.google.com/drive/folders/1eDFymBvtzUcjjwIT10G71Ek6UQn-CO4A?usp=drive_link](url)
