### ISSUE TITLE
Crash on Mac OSX

### ISSUE THREAD

**Issue by adrienneteicher** [git-moss/ProjectConverter#9]
Project Converter 1.2.1 on Mac OS 14.2.1

I was converting from a Bitwig generated DAWProject to a Reaper file.

Crash Report attached
[crashreport.txt](https://github.com/git-moss/ProjectConverter/files/13844034/crashreport.txt)

**Comment by git-moss** [comment]
Looks like an incompatibility with Macos. Does it happen with all projects?

**Comment by git-moss** [comment]
I can reproduce the issue but not sure what to do about it. It works fine when I build it locally. I changed the GitHub build to be run with the latest Macos and switch the JDK to 21 but with the same result.

**Comment by cristianvogel** [comment]
Also have instant crash in MacOs Ventura 13.6

**Comment by klangfuchs** [comment]
For me, it crashes when I hit the convert button for a file from Bitwig or Reaper on the macOS Sonoma 14.5.
Maybe it's a file permission thing.

**Comment by git-moss** [comment]
I just released a new build 1.2.2 which (at least on my system) fixes the crash. Please test.

**Comment by klangfuchs** [comment]
Yes, it works now! Thanks for caring ❤️
